=pod

=head1 NAME

Dancer2::Serializer::JSONMaybeXS - (DEPRECATED) Serializer for handling JSON data

=head1 SYNOPSIS

 use Dancer2;
 set serializer => 'JSONMaybeXS';

=head1 DESCRIPTION

This is a DEPRECATED serializer engine for the L<Dancer2> web framework.
L<Dancer2> now uses L<JSON::MaybeXS> natively in the default
L<Dancer2::Serializer::JSON> (as of version C<0.201000>), so this module is no
longer needed.

=head1 BUGS

Report any issues on the public bugtracker.

=head1 AUTHOR

Dan Book <dbook@cpan.org>

=head1 COPYRIGHT AND LICENSE

This software is Copyright (c) 2016 by Dan Book.

This is free software, licensed under:

  The Artistic License 2.0 (GPL Compatible)

=head1 SEE ALSO

L<Dancer2::Serializer::JSON>

=cut
