=pod

=head1 NAME

Dancer2::Serializer::JSONMaybeXS - Serializer for handling JSON data

=head1 SYNOPSIS

 use Dancer2;
 set serializer => 'JSONMaybeXS';

=head1 DESCRIPTION

This is a serializer engine for the L<Dancer2> web framework that allows you to
turn Perl data structures into JSON output and vice-versa. It uses
L<JSON::MaybeXS>, which is a faster and cleaner interface to JSON-encoding
modules than L<JSON>.pm.

=head1 METHODS

=head2 deserialize

 my $data = $serializer->deserialize($string);

Deserializes a JSON string into a Perl data structure.

=head2 serialize

 my $string = $serializer->serialize($data);

Serializes a Perl data structure into a JSON string.

=head1 BUGS

Report any issues on the public bugtracker.

=head1 AUTHOR

Dan Book <dbook@cpan.org>

=head1 COPYRIGHT AND LICENSE

This software is Copyright (c) 2016 by Dan Book.

This is free software, licensed under:

  The Artistic License 2.0 (GPL Compatible)

=head1 SEE ALSO

L<Dancer2>

=cut
